TOOLBOX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='homepage.html'), name='home'),
    path('', include('downloadApp.urls', namespace='downloadApp')),
    path('', include('imageApp.urls', namespace='imageApp'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

downloadApp/urls.py
from django.urls import path
from . import views

app_name = 'downloadApp'


urlpatterns = [
    path('videodownload/', views.home, name='home'),
]

imageApp/urls.py
from django.urls import path
from . import views

app_name = 'imageApp'

urlpatterns = [
    path('image/', views.home, name='home'),
]

downloadApp/forms.py
from django import forms

class DownloadVideoForm(forms.Form):
    
    link = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'm-auto w-full h-auto rounded p-2 text-black break-words', 'id':'link'}))
    
    video = forms.BooleanField(
        label='video', required=False, initial=True, widget=forms.CheckboxInput(attrs={'class': 'm-auto rounded w-5 h-5 ', 'id':'video'}))

    audio = forms.BooleanField(
        label='audio', required=False, widget=forms.CheckboxInput(attrs={'class': 'm-auto rounded w-5 h-5', 'id':'audio'}))

downloadApp/views.py
import os
from pytube import YouTube
from django.shortcuts import render

from .forms import DownloadVideoForm


def home(request):

    form = DownloadVideoForm()
    
    path = 'static/video'

    context =  {
        'title': 'Youtube Download',
        'filename': '',
        'thumbnail': '',
        'alert': '',
        'form': form
        }

    try:
        if len(os.listdir(path)) >= 1:

            for download in os.listdir(path):
                os.remove('{}/{}'.format(path, download))
    except:
        pass    


    if request.method == "POST":
        
        try:
            youtube = YouTube(request.POST['link'])
    
        except:
            context['alert'] = 'Link inválido!'
        
        else:
            
            match list(request.POST.keys())[-1]:

                case 'audio':
                    try:
                        filename = youtube.streams.get_audio_only().download(output_path=path)
                    except:
                        context['alert'] = 'Não foi possível baixar o áudio'

                case 'video':
                    try:
                        request.POST['video']
                        filename = youtube.streams.get_highest_resolution().download(output_path=path)
                    except:
                        context['alert'] = 'Não foi possível baixar video'

            try:
                filename = filename[filename.rindex('/'):]
                context['filename'] = 'video{}'.format(filename)
                context['thumbnail'] = youtube.thumbnail_url
            except:
                pass
        

    return render(request, template_name='download-home.html', context=context)

imageApp/views.py
from django.shortcuts import render

def home(request):

    context = {
        'title': 'Remove Background',
        'alert': ''
    }

    return render(request, template_name='image-home.html', context=context)

downloadApp/templates/download-home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<main class="container m-auto w-screen h-screen p-2">

    <section class="mt-[90px] w-full h-full rounded pb-5">

        {% if alert != '' %}
            <h1 class="m-auto text-center p-4 text-xl text-black">
                {{alert}}
            </h1>
        {% endif %}


        <h1 class="m-auto text-center p-4 text-xl text-black">
            Youtube Download
        </h1>

        <div class="grid gap-10 m-auto border rounded p-2 w-auto h-auto md:w-[500px] h-auto bg-black/90">

            <form method="post" action="" class="grid gap-5 h-full">

                {% csrf_token %}

                {{ form.link }}        

                <div class="grid grid-cols-2 w-full h-auto items-center text-center">
                    <span class="grid gap-3">
                        {{ form.video }}
                        {{ form.video.label }}
                    </span>
                    <span class="grid gap-3">
                        {{ form.audio }}
                        {{ form.audio.label }}        
                    </span>
                </div>
                
                <button type="submit" value="submit" class="m-auto p-2 bg-blue-500/50 border border-gray-500/50 text-center w-36 rounded text-xl
                    hover:border-white">
                        Get
                </button>

            </form>  



            {% if filename != '' %}                  
                <a href="{% static filename %}" download>            
                    <button class="m-auto p-2 bg-green-500/50 border border-gray-500/50 text-center w-full rounded text-xl
                        hover:border-white">
                            Download
                    </button>
                </a>            
            {% endif%}

        </div>
        

        {% if thumbnail != '' %}
            <div class="m-auto p-2 mt-10 w-auto h-auto md:w-[500px]">
                <img id="video-view" class="m-auto w-full h-full rounded" src="{{thumbnail}}">
            </div>
        {% endif %}

    </section>
</main>
    

{% endblock %}


{% block script %}

<script>
    let video = document.querySelector("#video")
    let audio = document.querySelector("#audio")
    
    function chooseType() {
    
        video.addEventListener("click", function () {
    
            audio.checked = ''
        })
    
        audio.addEventListener("click", function () {
    
            video.checked = ''
        })
    }
    
    chooseType()
</script>

{% endblock %}

imageApp/templates/image-home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<main class="container m-auto w-screen h-screen p-2">

    <section class="mt-[90px] w-full h-full rounded pb-5 ">
        
        {% if alert != '' %}
            <h1 class="m-auto text-center p-4 text-xl text-yellow-500/75">
                {{alert}}
            </h1>
        {% endif %}

        ..........
    </section>

</main>

{% endblock %}


{% block script %}
{% endblock %}

templates/base.html
<!DOCTYPE html>

<html>
    <head lang="pt-br">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        
        <title>
            {% block title %}
            {{ title }} | Toolbox
            {% endblock %}
        </title>

        {% block head %}
        {% endblock %}
        
        <!-- FAVICON -->
        <link rel="shortcut icon" href="https://github.com/Fernando-Medeiros.png">

        <!-- TAILWIND -->
        <script src="https://cdn.tailwindcss.com"></script>
    </head>


    <body class="font-primary bg-[#F2F2F2] text-[#F2F2F2]">

        {% include 'navbar.html'%}
        
        {% block content %}
        {% endblock %}
        
        {% include 'footer.html'%}

        {% block script %}
        {% endblock %}
        
        <!-- IONICONS -->
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

        <script type="text/javascript" src="/static/js/navbar.js"></script>
    </body>
<html>

templates/footer.html
<footer class="container m-auto w-full h-auto p-2 self-end">
    
    <div class="bg-black/10 w-full h-auto p-2">
    
    </div>

</footer>

templates/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Home-Page
{% endblock %}


{% block content%}


<main class="container m-auto p-2 w-screen h-auto">

    <!-- DOWNLOAD APP -->
    <section
        class="flex justify-around items-center mt-[90px] p-2 gap-3 border-b border-l border-gray-500/50 md:flex-row-2 flex-wrap drop-shadow-xl">

        <span class="grid gap-3 text-black">
            <h2 class="text-2xl bold">
                Download App
            </h2>
            <p>
                Você pode baixar a sua musica ou video favorito do youtube com o Download-App:
                <li> Extensão .mp4 </li>
                <li> Alta resolução </li>
                <li> Download de videos e musicas </li>
            </p>
            <a href="{% url 'downloadApp:home' %}"
                class="text-center p-2 w-fit transition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300 drop-shadow-xl">
                <ion-icon name="download-outline"
                    class="text-6xl m-auto text-[#345259] p-2 rounded-lg border border border-black/25 drop-shadow-xl">
                </ion-icon>
            </a>

        </span>
        <img src="{% static 'images/downloadapp.jpg' %}" class="p-2 w-96  rounded-full drop-shadow-xl">
    </section>


    <!-- IMAGE APP -->
    <section
        class="flex justify-around items-center p-2 gap-3 border-b border-r border-gray-500/50  md:flex-row-2 flex-wrap drop-shadow-xl">

        <img src="{% static 'images/imageapp.jpg' %}" class="p-2 w-96 rounded-full drop-shadow-xl">

        <span class="grid gap-3 text-black">
            <h2 class="text-2xl bold">
                Image App
            </h2>
            <p>
                Com o Image-App você pode editar rapidamente as suas imagens (jpg, png):
                <li> Remover o plano de fundo </li>
                <li> Converter a extensão </li>
                <li> Escalonar de forma eficiente </li>
            </p>

            <a href="{% url 'imageApp:home' %}"
                class="text-center p-2 w-fit transition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300 drop-shadow-xl">
                <ion-icon name="image-outline"
                    class="text-6xl m-auto text-[#345259]  p-2 rounded-lg border border border-black/25 drop-shadow-xl">
                </ion-icon>
            </a>
        </span>
    </section>


    <!-- QRCODE APP -->
    <section
        class="flex justify-around items-center p-2 gap-3 border-b border-l border-gray-500/50  md:flex-row-2 flex-wrap drop-shadow-xl">

        <span class="grid gap-3 text-black">
            <h2 class="text-2xl bold">
                QR-Code App
            </h2>
            <p>
                .......................................................................
                <li>..............................................</li>
                <li>..............................................</li>
            </p>
            <a href="{% url 'home' %}"
                class="text-center p-2 w-fit transition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300 drop-shadow-xl">
                <ion-icon name="qr-code-outline"
                    class="text-6xl m-auto text-[#345259]  p-2 rounded-lg border border border-black/25 drop-shadow-xl">
                </ion-icon>
            </a>
        </span>

        <img src="{% static 'images/qrcodeapp.jpg' %}" class="w-96 rounded-full drop-shadow-xl">
    </section>


    <!-- PDF APP -->
    <section
        class="flex justify-around items-center p-2 gap-3 border-b border-r border-gray-500/50  md:flex-row-2 flex-wrap drop-shadow-xl">

        <img src="{% static 'images/pdfapp.jpg' %}" class="p-2 w-96 rounded-full drop-shadow-xl">

        <span class="grid gap-3 text-black">
            <h2 class="text-2xl bold">
                Pdf App
            </h2>
            <p>
                .......................................................................
                <li>..............................................</li>
                <li>..............................................</li>
            </p>

            <a href="{% url 'home' %}"
                class="text-center p-2 w-fit transition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300 drop-shadow-xl">
                <ion-icon name="document-text-outline"
                    class="text-6xl m-auto text-[#345259]  p-2 rounded-lg border border border-black/25 drop-shadow-xl">
                </ion-icon>
            </a>
        </span>
    </section>


    <!-- ANALYSIS APP -->
    <section
        class="flex justify-around items-center p-2 gap-3 border-b border-l border-gray-500/50  md:flex-row-2 flex-wrap drop-shadow-xl">

        <span class="grid gap-3 text-black">
            <h2 class="text-2xl bold">
                Analysis App
            </h2>
            <p>
                .......................................................................
                <li>..............................................</li>
                <li>..............................................</li>
            </p>
            <a href="{% url 'home' %}"
                class="text-center p-2 w-fit transition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300 drop-shadow-xl">
                <ion-icon name="analytics-outline"
                    class="text-6xl m-auto text-[#345259]  p-2 rounded-lg border border border-black/25 drop-shadow-xl">
                </ion-icon>
            </a>
        </span>

        <img src="{% static 'images/analysisapp.jpg' %}" class="p-2 w-96 h-96 rounded-full drop-shadow-xl">
    </section>


</main>


{% endblock %}

templates/navbar.html
<nav class="fixed z-40 w-screen p-2 h-auto self-start bg-[#1A1F26]  text-[#F2F2F2]/75">

    <div class="container m-auto flex gap-5 justify-between items-center w-full">

        <a href="{% url 'home' %}"
            class="pt-2 text-5xl hover:text-white -translate-y-1 hover:scale-110 hover: duration-300">
            <ion-icon name="cube-outline"></ion-icon>
        </a>


        <!-- LINKS MOBILE -->

        <button id="menu"
            class="flex items-center gap-4 md:hidden ransition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300">
            <ion-icon name="menu-outline" class="text-3xl"></ion-icon>
        </button>


        <!-- LINKS DEFAULT -->
        <nav class="hidden  w-full h-auto gap-10 justify-evenly  md:flex">
            <a href="{% url 'downloadApp:home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
                Download
            </a>
            <a href="{% url 'imageApp:home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
                Image
            </a>
            <a href="{% url 'home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
                QR-Code
            </a>
            <a href="{% url 'home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
                PDF
            </a>
            <a href="{% url 'home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
                Analysis
            </a>
        </nav>



        <!-- CONTACT -->
        <div class="flex items-center w-auto h-auto gap-5 pt-2 pr-2 md:gap-10">

            <a href="https://github.com/Fernando-Medeiros" target="blank"
                class="transition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300">
                <ion-icon name="logo-github" class="text-3xl"></ion-icon>
            </a>

            <a href="https://www.linkedin.com/in/fernando-de-alvarenga-medeiros-037306207/" target="blank"
                class="transition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300">
                <ion-icon name="logo-linkedin" class="text-3xl"></ion-icon>
            </a>

            <a href="https://www.youtube.com/channel/UC4DtvxaUeEZHmqafh5mSOLg" target="blank"
                class="transition ease-in-out delay-150 hover:text-white -translate-y-1 hover:scale-110 hover: duration-300">
                <ion-icon name="logo-youtube" class="text-3xl"></ion-icon>
            </a>
        </div>

    </div>

    <nav id="pages" class="flex w-full h-full flex-wrap gap-5 pt-5 justify-around hidden">
        <a href="{% url 'downloadApp:home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
            Download
        </a>
        <a href="{% url 'imageApp:home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
            Image
        </a>
        <a href="{% url 'home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
            QR-Code
        </a>
        <a href="{% url 'home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
            PDF
        </a>
        <a href="{% url 'home' %}" class="hover:text-white -translate-y-1 hover: duration-300">
            Analysis
        </a>
    </nav>
</nav>